### ISSUE TITLE
Fjerne regler for Data-Temaer

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-reasoning-service#166]
## Nåværende oppførsel
Hvis en datasettbeskrivelse inneholder tripler om et Tema, f.eks. en egen label, blir disse lagt til.

F.eks. om jeg lager en datasettbeskrivelse som peker til DataTheme ECON, og i tillegg definerer triplet
`<http://publications.europa.eu/resource/authority/data-theme/ECON> skos:prefLabel "Ikke-relatert label"@nb`

legges det til en bokmåls-labelen på ECON-koden i kontekst av datasettbeskrivelsen.

Uklart hvordan dette vises i portal per nå.

Gjelder temaer fra EuroVoc, Los, og DataTheme.

## Forslag
Fjerne custom regler for Temaer.

**Comment by oystein-asnes** [comment]
Dette var snåle greier! prefLabels er definert av sjølve vokabulara og det bør være lange fengselsstraffer for å lage eigne labels på denne måten. DataTheme og Los har labels både på nynorsk, bokmål og engelsk ++ by design. 

EuroVoc har ikkje norske labels. Kan dette være ein hack for å komme rundt det? Det er forresten ikkje usannsynelg at kravet om bruk av Eurovoc vil forsvinne frå DCAT-AP-NO. Eg tvilar på at det er i bruk i dag. 

Samtidig er det lov å bruke andre vokabular med andre termar feks til å beskrive datasett. Kravet for DataTheme er at det må være eit publisert SKOS-vokabular og at sjølve vokabularet temaet er henta må bli referert til som "tematisk skjema" .

Støttar forslaget om å fjerne skreddarsaum rundt dette.

**Comment by NilsOveTen** [comment]
@oystein-asnes Fikler litt med dette atm, men siden jeg allerede gjør litt her så kan jeg kanskje også gjøre litt med reasoning-reglene til datasett vi bruker mtp LOS og DataThemes.

Nå legges det til data-theme hvis det ligger et los-tema på datasettet som peker til gitt data-theme som exactMatch, closeMatch eller broadMatch. Skal jeg også legge til det omvendte? Da kanskje kun for exactMatch?

Dvs los-tema blir lagt til hvis datasettet har et data-theme som tema og LOS sier at gitt los-tema er exactMatch til data-theme som refereres til på datasettet

**Comment by oystein-asnes** [comment]
Ja takk, begge veier. Men: Pga. Los-revisjon som pågår og som peker i retning av at Los-temaene blir betydelig endret (inkl. URIer), er det argument for å vente med å peke fra Data theme til Los-temaer. Uansett best å holde seg til excactMatch.

**Comment by NilsOveTen** [comment]
Ok, avventer til LOS-revisjonen er ferdigstilt 👍
